---

galaxy_info:
  author: "Desiree Yahya"
  description: Ansible role for installing and Configuration SNMP v3.
  license: MIT
  min_ansible_version: 2
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Archlinux
      versions:
        - all

  galaxy_tags:
    - system
    - networking
    - monitoring

dependencies: []
