---
- name: Create EC2 Instance(s)
  ec2:
    group_id: '{{ ec2_server_security_group }}'
    count: '{{ ec2_server_instcount }}'
    instance_type: '{{ ec2_server_instance_type }}'
    image: '{{ ec2_server_image }}'
    wait: true
    region: '{{ ec2_server_region }}'
    keypair: '{{ ec2_server_keypair }}'
    aws_access_key: '{{ ec2_server_access_key }}'
    aws_secret_key: '{{ ec2_server_secret_key }}'
    instance_tags:
      Name: '{{ ec2_server_name }}'
      Group: '{{ ec2_group_name }}'
  register: ec2

- name: Instance Ids
  debug: msg={{ item.id }}
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH
  wait_for:
    host: '{{ item.public_dns_name }}'
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"

- name: Add hosts group temporary inventory group with pem path
  add_host: hostname={{ item.public_ip }} groups=ec2hosts
  loop: "{{ ec2.instances }}"
