- hosts: "{{target}}"
  tasks:
    - debug:
        msg: "Base playbook"

- import_playbook: satellite.yml
- import_playbook: selinux.yml
- import_playbook: sssd.yml
- import_playbook: sudo.yml
- import_playbook: java.yml
- import_playbook: snmp.yml
- import_playbook: vmtools.yml
