- hosts: "{{target}}"
  tasks:
    - name: Create a temp resolv.conf
      copy:
        content: |
          nameserver { nameserver1 }
          nameserver { nameserver2 }
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
