- name: Check hosts
  hosts: "{{target}}"
  gather_facts: no
  tasks:
    - set_fact:
        hosts_confirmed: true
      delegate_to: localhost
      delegate_facts: true

- name: Verify hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - assert:
        that: hosts_confirmed | default(false)

- name: Spin Up EC2 Server
  hosts: "{{target}}"
  vars_files: 
    - group_vars/vault.yml
  roles:
    - role: ec2_server
