---
- name: Heal Memory
  hosts: "{{target}}"
  vars:
    memthreshold: 75
  tasks: 
    - name: Register memusage var
      shell: "/usr/bin/ps -eo %mem,size,user,pid | sort -rnk 1 | head -n 1 | xargs"
      args:
        warn: false
      register: memusage

    - name: Register mempercent var
      shell: "/usr/bin/ps -eo %mem | sort -rnk 1 | head -n 1 | xargs"
      args:
        warn: false
      register: mempercent

    - name: Register memowner var
      shell: "/usr/bin/ps -eo %mem,size,user,pid | sort -rnk 1 | head -n 1 | awk '{print $3}'"
      args:
        warn: false
      register: memowner
      
    - name: Register mempid var
      shell: "/usr/bin/ps -eo %mem,size,user,pid | sort -rnk 1 | head -n 1 | awk '{print $4}'"
      args:
        warn: false
      register: mempid
 
    - name: Restart JBOSS process if needed
      service:
        name: eap72
        state: restarted
      when: "mempercent.stdout|int > memthreshold|int and 'jboss' in memowner.stdout"
      
    - name: Restart Apache process if needed
      service:
        name: httpd
        state: restarted
      when: "mempercent.stdout|int > memthreshold|int and 'apache' in memowner.stdout"
      
    - name: Kill Non-Common agent if needed
      shell: "/usr/bin/kill -HUP {{mempid.stdout}}"
      when: "mempercent.stdout|int > memthreshold|int and 'jboss' not in memowner.stdout and 'apache' not in memowner.stdout"
      
    - name: All memory within threshold. No Tasks Done
      debug:
        msg:
          - "All memory within acceptable limits!"
      when: "mempercent.stdout|int < memthreshold|int"
