---
- name: Configure EC2 Hostname
  hosts: "{{target}}"
  gather_facts: false
  pre_tasks:
    - raw: yum -y install python
  tasks:
    - name: Update hostname with ec2_server_name
      hostname:
        name: '{{ inventory_hostname }}.{{ domain_name }}'

    - name: Update /etc/hosts with hostname
      lineinfile:
        dest: /etc/hosts
        regexp: "^127.0.0.1"
        line: "127.0.0.1{{'\t'}}{{ inventory_hostname }} {{ inventory_hostname }}.{{ domain_name }} localhost localhost.localdomain"
        state: present

    - name: Update /etc/resolv.conf
      lineinfile:
        dest: /etc/resolv.conf
        regexp: "^search"
        line: "search {{ domain_name }}"
        state: present
