- name: Check hosts
  hosts: "{{target}}"
  gather_facts: no
  tasks:
    - set_fact:
        hosts_confirmed: true
      delegate_to: localhost
      delegate_facts: true

- name: Verify hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - assert:
        that: hosts_confirmed | default(false)

- name: Install NTP
  hosts: "{{target}}"
  roles:
    - role: ntp
      vars:
        ntp_servers:
          - ntp.pool.org
