---
- import_playbook: java.yml
  vars:
    java_version: 8

- name: Install Git
  yum:
    name: git
    state: latest

- name: Install Spring Boot Project
  hosts: "{{target}}"
  roles:
    - role: spring_boot
