---
galaxy_info:
  author: 
  description:
  company: 
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.9.2
  platforms:
  - name: 
    versions:
    - all
  - name:
    versions:
    - all
  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
  categories:
  #- cloud
  - cloud:ec2
  #- cloud:gce
  #- cloud:rax
  #- clustering
  #- database
  #- database:nosql
  #- database:sql
  #- development
  #- monitoring
  #- networking
  #- packaging
  #- system
  #- web
dependencies:
  - role: required_vars

