---
ntp_enabled: true
ntp_timezone: Etc/UTC

ntp_manage_config: false

# NTP server area configuration (leave empty for 'Worldwide').
# See: http://support.ntp.org/bin/view/Servers/NTPPoolServers
ntp_area: ''
ntp_servers:
  - "ntp1.com"
  - "ntp2.com"
ntp_restrict:
  - "127.0.0.1"
  - "::1"
