---
# handlers file for sbaerlocher.snmp

- name: restart snmp
  become: true
  service:
    name: "{{ snmp_service_name }}"
    state: restarted

- name: enabled snmp
  become: true
  service:
    name: "{{ snmp_service_name }}"
    enabled: true

- name: start snmp
  become: true
  service:
    name: "{{ snmp_service_name }}"
    state: started
