---
- name: Prepare instance for role execution
  hosts: all
  become: true
  tasks:
    - name: Create Nginx Directory
      file:
        path: /var/log/nginx
        state: directory
        owner: root
        group: sys
        mode: 0775
    - name: Create Files
      file:
        path: /var/log/nginx/access.log
        state: touch
        owner: root
        group: sys
        mode: 0775
    - name: Create Files
      file:
        path: /var/log/nginx/error.log
        state: touch
        owner: root
        group: sys
        mode: 0775
