---
- name: Install Git
  yum:
    name: git
    state: latest

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/projects
    state: directory
    mode: '0755'

- name: Clone The Project
  ansible.builtin.git:
    repo: "https://github.com/Nsteinbaugh/{{ spring_boot_project_name }}.git"
    dest: "/var/projects/{{ spring_boot_project_name }}"
    clone: yes
    update: yes
    force: yes

- name: check for gradle
  stat:
    path: "/var/projects/{{ spring_boot_project_name }}/gradlew"
  register: gradle

- name: check for maven
  stat:
    path: "/var/projects/{{ spring_boot_project_name }}/mvnw"
  register: maven

- name: set gradle permissions
  shell: "chmod 755 /var/projects/{{ spring_boot_project_name }}/gradlew"
  args:
    warn: false
  when: gradle.stat.exists

- name: set maven permissions
  shell: "chmod 755  /var/projects/{{ spring_boot_project_name }}/mvnw"
  args:
    warn: false
  when: maven.stat.exists

- name: Run Project (Gradle)
  shell: "nohup /var/projects/{{ spring_boot_project_name }}/gradlew bootRun </dev/null >/dev/null 2>&1 &"
  when: gradle.stat.exists
  become: yes

- name: Run Project (Maven)
  shell: "nohup /var/projects/{{ spring_boot_project_name }}/mvnw bootRun </dev/null >/dev/null 2>&1 &"
  when: maven.stat.exists
  become: yes
