---
# tasks file for patch
#

#- name: Create systemStateCheck - /usr/local/sbin/systemStateCheck.sh
#  template: src=systemStateCheck.j2 dest=/usr/local/sbin/systemStateCheck.sh owner=root mode=0770

#- name: Cron systemStateCheck
#  cron:
#    name: "Setup cron"
#    minute: "0"
#    hour: "5"
#    job: "/usr/local/sbin/systemStateCheck.sh"
#    user: root
#    state: present

#- name: Run systemStateCheck
#  shell: "/usr/local/sbin/systemStateCheck.sh"

- name: Run yum update
  shell: "yum update -y > /usr/local/sbin/yumlog"

- name: Check in yum log requires a reboot
  shell: "grep -i 'No Packages marked for Update' /usr/local/sbin/yumlog"
  args:
    warn: false
  register: yum_log 
  changed_when: no
  ignore_errors: yes

- name: Reboot server
  shell: "/sbin/shutdown -r +1 &"
  when: yum_log.rc == 1
  
- name: Check to make sure reboot has completed
  wait_for_connection:
    delay: 60
    sleep: 30
    timeout: 600 
 
