---
splunk_forwarder_user: "splunk"
splunk_forwarder_group: "splunk"
splunk_forwarder_uid: "10011"
splunk_forwarder_gid: "10011"
splunk_release: "8.2.2.1"
# splunk_url: "https://download.splunk.com/products/universalforwarder/releases/{{ splunk_release }}/linux"
splunk_url: "https://d7wz6hmoaavd0.cloudfront.net/products/universalforwarder/releases/{{ splunk_release }}/linux"
splunk_forwarder_rpm: "splunkforwarder-8.2.2.1-ae6821b7c64b-linux-2.6-x86_64.rpm"
splunk_forwarder_deb: "splunkforwarder-8.2.2.1-ae6821b7c64b-linux-2.6-amd64.deb"
splunk_rpm: "{{ splunk_url }}/{{ splunk_forwarder_rpm }}"
splunk_deb: "{{ splunk_url }}/{{ splunk_forwarder_deb }}"
splunk_deb_checksum: "md5:ec83646e89d01784633cee034f0e42da"
splunk_rpm_checksum: "md5:bbaf0e0d8a50af498ff2221428ff125f"


# These may be removed at some point, but they are placeholders so I don't forget to set them
splunk_forwarder_indexer: "splunk-indexer:9997"
splunk_forwarder_index: "default"
splunk_forwarder_sourcetype: "nginx"

splunk_forwarder_logs:
  - /var/log/nginx/access.log
  - /var/log/nginx/error.log
