---
- name: Download the Spring Boot demo
  get_url:
    url: "{{ spring_boot_url }}"
    dest: "/tmp/{{ spring_boot_demo_version }}"

- name: Run the Spring Boot demo
  shell: nohup java -jar /tmp/demo-0.1.0-SNAPSHOT.jar </dev/null >/dev/null 2>&1 &