---

#Install the base software
- name: "Debug"
  debug:
    msg: "{{
    satellite_deployment_packages[satellite_deployment_version | string] +
    satellite_deployment_extra_packages + satellite_deployment_plugin_packages
    }}"
- name: "Install_software"
  become: "yes"
  yum:
    name: "{{
    satellite_deployment_packages[satellite_deployment_version | string] +
    satellite_deployment_extra_packages + satellite_deployment_plugin_packages
    }}"
    state: "latest"
    async: 1000
    poll: 0
    register: sat_sleeper

- name: 'YUM - check on satellite installation'
  async_status: jid={{ sat_sleeper.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 50
