---
- include: set_facts.yml
- include: registration.yml
#  when: satellite_connected
#- include: firewall.yml
- include: install_software.yml
- include: install_satellite.yml
- include: configure_satellite.yml
  when: satellite_state == 'install'

- include: uninstall.yml
  when: satellite_state == 'uninstall'
