---
- name: "Disable EPEL repository"
  yum_repository:
    name: epel
    state: absent

- name: "RHN | registering system with RHN"
  redhat_subscription:
    state: "present"
    username: "{{ satellite_deployment_rhn_user }}"
    password: "{{ satellite_deployment_rhn_password }}"
    consumer_name: "{{ satellite_deployment_hostname_full }}"
    pool_ids: "{{ satellite_deployment_pool_id }}"

- name: Disable all RHSM repositories first
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable necessary Satellite6 repositories
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items:
     - rhel-7-server-satellite-{{ satellite_deployment_version }}-rpms
     - rhel-7-server-rpms
     - rhel-server-rhscl-7-rpms
     - rhel-7-server-satellite-maintenance-6-rpms
     - rhel-7-server-ansible-2.8-rpms

- name: "Remove the RHUI client on AWS systems"
  yum:
    name: 'rh-amazon-rhui-client*'
    state: absent

- name: Update /etc/yum/pluginconf.d/product-id.conf
  lineinfile:
    dest: /etc/yum/pluginconf.d/product-id.conf
    regexp: "^enabled"
    line: "enabled=1"
    state: present

- name: "RHN | Perform yum update of the whole system"
  yum:
    name: '*'
    state: latest
